apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pvys
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pvys
    app.kubernetes.io/part-of: tkwch-fix-0075-0031-app
  name: devfile-sample-pvys
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-pvys
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-pvys
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0-7-tenant/tkwch-fix-0075-0031-app/devfile-sample-pvys@sha256:372d19e47b8e79f90f0fbe48bfb3ab6f435744239be23a5a51ce0269af1001c3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
